exclude: 'docs/'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
        verbose: true
        exclude: '__init__.py'

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ['--profile', 'black']
        verbose: true
        exclude: '__init__.py'
